default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [ --unsafe ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [ "--filter-files" ]
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.981
    hooks:
      - id: mypy
        exclude: tests/
        pass_filenames: false
        args: ["--ignore-missing-imports", "--scripts-are-modules", elhub_sdk]
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=120, --safe, --quiet]
